# Generated by Django 4.2.19 on 2025-02-13 16:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DPJP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DPJP',
                'verbose_name_plural': 'DPJPs',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dpjp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dpjp', verbose_name='DPJP'),
        ),
    ]
