# Generated by Django 4.2.19 on 2025-02-13 16:47

from django.db import migrations

def create_initial_dpjp(apps, schema_editor):
    DPJP = apps.get_model('core', 'DPJP')
    Patient = apps.get_model('core', 'Patient')
    
    # Create the initial DPJP
    dpjp = DPJP.objects.create(
        name='Dirwan',
        is_active=True
    )
    
    # Update all existing patients to use this DPJP
    Patient.objects.all().update(dpjp=dpjp)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dpjp_alter_patient_date_of_admission_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_dpjp),
    ]
